# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER richard

# 挂载目录
VOLUME /home/ruoyi
# 创建目录
RUN mkdir -p /home/ruoyi
# 指定路径
WORKDIR /home/ruoyi
# 复制jar文件到路径
COPY ./jar/education-admin.jar /home/ruoyi/education-admin.jar
# 启动系统服务
ENTRYPOINT ["java","-jar","education-admin.jar"]